org: yieldx
app: lambdas-shoebox
service: lambdas-shoebox

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs16.x
  profile: yieldx

functions:
  get_reports:
    handler: get_reports.default
    events:
      - http:
          method: get
          path: get-reports
          integration: lambda
          cors: true
          request:
            parameters:
              querystrings:
                username: false
            template:
              application/json: |
                { 
                  "username" : "$input.params('username')"
                }

  get_devices:
    handler: get_devices.default
    events:
      - http:
          method: get
          path: get-devices
          integration: lambda
          cors: true
          request:
            parameters:
              querystrings:
                username: false
                mqttAddress: false
            template:
              application/json: |
                { 
                  "username" : "$input.params('username')",
                  "mqttAddress" : "$input.params('mqttAddress')"
                }

  get_last_sensors:
    handler: get_last_sensors.default
    events:
      - http:
          method: get
          path: get-last-sensors
          integration: lambda
          cors: true
          request:
            parameters:
              querystrings:
                MAC: true
            template:
              application/json: |
                { 
                  "MAC" : "$input.params('MAC')"
                }

  get_ota_list:
    handler: get_ota_list.default
    events:
      - http:
          method: get
          path: get-ota-list
          integration: lambda
          cors: true
