org: yieldx
app: lambdas-shoebox
service: lambdas-shoebox

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs16.x
  profile: yieldx

functions:
  get_reports:
    handler: get_reports.default
    events:
      - http:
          method: get
          path: get-reports
          integration: lambda
          cors: true
